version: '3.8'

services:
  # Backend service
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: node-app:latest
    container_name: node-app-container
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network
    # Optional dev volume for hot reload
    volumes:
      - ./backend:/app
      - /app/node_modules

  # MongoDB service
  mongo:
    image: mongo:6.0
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Frontend service
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react-app:latest
    container_name: react-app-container
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    # Optional dev volume for hot reload
    volumes:
      - ./frontend:/app
      - /app/node_modules

# Docker network
networks:
  app-network:
    driver: bridge

# Persistent volume for MongoDB
volumes:
  mongo-data:
