version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myapp-frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: myapp-backend
    command: npm start
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - my-network
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: myapp-mongo
    ports:
      - "27017:27017"           # Allows host (Compass) to connect via localhost
    volumes:
      - data-volume:/data/db    # Persists MongoDB data
    networks:
      - my-network

volumes:
  data-volume:

networks:
  my-network:
    driver: bridge
